name: test
on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npx tsc

  test-postgres:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
        postgres-version: [11]
    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_DB: patch_knex
          POSTGRES_USER: virk
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
      postgres_replica:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_DB: patch_knex
          POSTGRES_USER: virk
          POSTGRES_PASSWORD: secret
        ports:
          - 5433:5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run Postgres Tests
        run: npm run test:pg

  test-mysql:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mysql: [{ version: 5.7, command: 'test:mysql' }, { version: 5.7, command: 'test:mysql2' }]
        node-version: [16]
    services:
      mysql:
        image: mysql:${{ matrix.mysql.version }}
        env:
          MYSQL_DATABASE: patch_knex
          MYSQL_USER: virk
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - '3306:3306'
      mysql_replica:
        image: mysql:${{ matrix.mysql.version }}
        env:
          MYSQL_DATABASE: patch_knex
          MYSQL_USER: virk
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - '3307:3306'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run Mysql Tests
        run: npm run ${{command}}
  test-mssql:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: 'arandom&233password'
          ACCEPT_EULA: 'Y'
        ports:
          - '1433:1433'
      mssql_replica:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: 'arandom&233password'
          ACCEPT_EULA: 'Y'
        ports:
          - '1434:1433'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run Mssql Tests
        run: npm run test:mssql
